# https://taskfile.dev

version: '3'

vars:
  DB_URL: postgres://postgres:postgres@localhost:5432/auth
  MIGRATION_NAME: initial
  CONFIG_PATH: ./config/local.yaml

tasks:
  run:
    cmds:
      - CONFIG_PATH={{.CONFIG_PATH}} go run ./cmd/auth
  build:
    cmds:
      - go build -o ./bin/auth ./cmd/auth
  lint:
    cmds:
      - golangci-lint --timeout=2m run
  test:
    cmds:
      - go test -short -race -count=1 -timeout 30s ./...
  clean:
    cmds:
      - rm -rf ./bin
  migrate-new:
    cmds:
      - migrate create -ext sql -dir ./internal/data -seq {{.MIGRATION_NAME}}
  migrate-up:
    cmds:
      - migrate -path ./internal/data -database '{{.DB_URL}}?sslmode=disable' up
  migrate-down:
    cmds:
      - migrate -path ./internal/data -database '{{.DB_URL}}?sslmode=disable' down
