http_port: localhost:8081
jwt_secret: secret
access_token_ttl: 2m
refresh_token_ttl: 10h
db_url: postgres://postgres:postgres@localhost:5432/auth
log_level: info
webhook_url: http://localhost:9091/webhook